package com.surplus.task.utils;

public enum EnumTransactionStatus {
	PAYMENT_DONE_BY_BUYER,MONEY_RESERVED_BY_ADMIN,MATERIAL_DISPATCHED_BY_SELLER,MATERIAL_REACHED_BUYER,
	MATERIAL_APPROVED_BY_BUYER, MONEY_TRANSFERRED_TO_SELLER,MONEY_REACHED_TO_SELLER,TRANSACTION_COMPLETED
}
